### PR TITLE
Use openziti provider

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by dariuszSki** [comment]
It looks like you are splitting the original plan into 2. One to create cluster, ziti console and controller, and the second one to create edge router?

**Comment by qrkourier** [comment]
That's right. I'm still working on the README updates to explain that. I'll mark this PR as a draft until I'm done with that part.

**Comment by qrkourier** [comment]
@dariuszSki ready for testers on this. Merging this is blocked by https://github.com/openziti/helm-charts/pull/69. Will you review that chart change?

**Review by dariuszSki — APPROVED** [review]
not sure if you are done, I will take it for a spin next week to test it myself. :)

**Comment by qrkourier** [comment]
I'm continuing to work in another branch, so this one should test out for you as written.

**Pull request merged**
